### ISSUE TITLE
How to load a basis file at on demand

### ISSUE THREAD

**Issue by sarangborude** [atteneder/KtxUnity#23]
Currently the textures is loaded in the Start function, Is it possible that I pass a path to a .basis file and the texture gets loaded on demand in the middle of an execution of a script?

**Comment by sarangborude** [comment]
Would be nice to have a function 
Texture 2D texture = LoadBasisTexture(<path to file>)

**Comment by hybridherbst** [comment]
I think you should be able to do

```
var basis = new BasisUniversalTexture();
basis.onTextureLoaded += (tex, orientation) => texture = tex;
basis.LoadFromUrl(absPath, this);
```

however there seems to currently be a bug with that in the latest version (#21).

**Comment by atteneder** [comment]
Thanks for your inputs!

> Texture 2D texture = LoadBasisTexture()

This implies not just explicit loading, but also synchronous (which can cause frame stalls, so I'd discourage you to do that during game play)

@hybridherbst 's solution is explicit, but async, so that's great.

We should probably extend the *Usage* section in the README.md to cover this use case.

**Comment by sarangborude** [comment]
@atteneder My use case requires me to download the textures from an API at run time and then I have to decompress it.  I might just decompress in a background thread and that might resolve the stalling issue. 

@hybridherbst Thanks, I will try that out.

**Comment by atteneder** [comment]
> My use case requires me to download the textures from an API at run time and then I have to decompress it. I might just decompress in a background thread and that might resolve the stalling issue.

If you load it like suggested, it already IS decompressed in a background thread. That's why I endorsed this solution :)

**Comment by hybridherbst** [comment]
@atteneder maybe a good future thing is to implement background texture GPU upload. It certainly works on Android and iOS, and I think I've seen Windows Desktop implementations, but not sure about the latter. That would definitely speed things up quite a bit on top of the already great gains that glTFast brings.

**Comment by atteneder** [comment]
> @atteneder maybe a good future thing is to implement background texture GPU upload. It certainly works on Android and iOS, and I think I've seen Windows Desktop implementations, but not sure about the latter. That would definitely speed things up quite a bit on top of the already great gains that glTFast brings.

Absolutely!

I presume you mean by using native Graphics APIs (OpenGL,Vulkan,etc.) instead of Unity's API, right? We would then create the Unity Texture object via [Texture2D.CreateExternalTexture](https://docs.unity3d.com/ScriptReference/Texture2D.CreateExternalTexture.html).

This would probably be faster for two reasons:

- Upload in background thread
- No need to re-sort mipmap chains (has to be done atm, since Unity expects them in different order :-1:  )

Only disadvantage: Needs implementations per Graphics API (Vulkan, Metal, D3D, etc.). KTX-Software comes with native uploads for OpenGL and Vulkan already, so that might be a great starting point.

Let me know your thoughts and if you meant something different.

Thanks!
