### ISSUE TITLE
Incorrect color channel after importing

### ISSUE THREAD

**Issue by ApprenticeGC** [atteneder/KtxUnity#66]
I use the image downloaded from [this site](https://samplefilehub.com/img/heic-sample-file-download/). Using [libvips cli tool](https://www.libvips.org/API/current/using-cli.html) on linux Ubuntu 22.04 to convert heic format of image to png format.

The command I use is

`vips pngsave samplefilehub.heic samplefilehub.png`

After getting samplefilehub.png, I use the tool(toktx) provided by [KTX-Software](https://github.khronos.org/KTX-Software/ktxtools/toktx.html) also on Ubuntu 22.04

The command for making ktx2 format is the following

`
OUT_FILE="samplefilehub.ktx2" \
IN_FILE="samplefilehub.png" \
&& time ./bin/toktx \
    --t2 \
    --assign_oetf srgb \
    --genmipmap \
    --encode astc \
    --astc_blk_d 6x6 \
    --astc_quality fastest \
    --bcmp \
    --lower_left_maps_to_s0t0 \
    ${OUT_FILE} \
    ${IN_FILE}
`

After importing to Unity
It shows [like this](https://pasteboard.co/sJdk8DOLaYUk.png)
while it should look [like this](https://pasteboard.co/vR55BN6PnBVp.png) originally.

I notice that the importer will use B5G6B5 format, is this correct result?

**Comment by atteneder** [comment]
Hi @ApprenticeGC ,

I could reproduce the issue. Yes, the texture format choice was bad and that's why it ended up with wrong colors. I've already made the fixing changes in branch `ktx-`, to be released soon.

I'm also thinking about lettting user override the format in the importer. That would make it a lot more useful.

Thanks for reporting!

P.S.: in you conversion command, `toktx` ignores all ASTC parameters and only takes `--bcmp`.
