### ISSUE TITLE
Unity 6 webGL emscripten compatibility issue

### ISSUE THREAD

**Issue by joecat88** [atteneder/KtxUnity#94]
Hi, I have a unity webgl project and for company reasons I upgraded to Unity 6. Now when I try to build, I recieve an error related to ktx package. I asked to unity support, and they said that the only solution is to recompile the native plugin of ktx package with Emscripten 3.1.38, as you can read on the last 4 comments of this thread: 

https://discussions.unity.com/t/unity-6000-webgl-build-error-on-using-a-package/1500409/10

Can someone help me with this issue?
Thanks

**Comment by atteneder** [comment]
Hi,

sure I can offer help.

Instead of using this repository (or the OpenUPM package), replace it with the fork [KTX for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@latest/) (provided officially by Unity).

Full disclosure: I started this package/repository, was hired by Unity and kept developing it in an internal fork that is now way ahead of this version. At some point we will sync them or deprecate this version.

hth
